# Generated by Django 4.0.5 on 2022-06-29 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='품목')),
                ('category', models.CharField(max_length=128, verbose_name='카테고리')),
                ('information', models.TextField(verbose_name='상품정보')),
                ('image', models.ImageField(default='default.png', upload_to='product/', verbose_name='상품사진')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_user_profile', to='users.profile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_user', to=settings.AUTH_USER_MODEL)),
                ('wish', models.ManyToManyField(blank=True, related_name='products_wish', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
